### ISSUE TITLE
Dev Tasks Overview

### ISSUE THREAD

**Issue by matsair** [matsair/NutSmoothie#1]
- [x] Data storage @matsair
- [x] Maps integration + Maps screen #activity @matsair
- [x] Main screen #activity @Jojo2511 
- [x] Location list #activity @rich89 
- [x] Location tracking #service  @JanWe92
- [x] Notifications @JanWe92
- [x] New task screen (activity or dialog or fragment...) @Jojo2511

**Comment by FlyLongSky** [comment]
Mats, uploaded activities and frontend-classes?

Jo

**Comment by matsair** [comment]
Habs per Email geschickt!

**Comment by matsair** [comment]
done!
